// GENERATED CODE - Hive Type Adapter for Flashcard
// Do not edit manually - generated by build_runner

part of 'flashcard.dart';

class FlashcardAdapter extends TypeAdapter<Flashcard> {
  @override
  final int typeId = 0;

  @override
  Flashcard read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (int i = 0; i < numOfFields; i++) {
      final fieldKey = reader.readByte();
      fields[fieldKey] = reader.read();
    }
    final value = Flashcard(
      id: fields[0] as String,
      question: fields[1] as String,
      answer: fields[2] as String,
    );
    value.createdAt = fields[3] as DateTime;
    return value;
  }

  @override
  void write(BinaryWriter writer, Flashcard obj) {
    writer
      ..writeByte(4)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.question)
      ..writeByte(2)
      ..write(obj.answer)
      ..writeByte(3)
      ..write(obj.createdAt);
  }
}